# Generated by Django 4.0.3 on 2022-04-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='langs',
            new_name='notes',
        ),
    ]
